version: '3.8'

services:
  episode13475-real:
    build:
      context: .
      dockerfile: Dockerfile.episode13475
    container_name: episode13475-real-trading
    ports:
      - "8082:8082"
    volumes:
      - ./checkpoints:/app/checkpoints:ro
      - ./data:/app/data:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8082')"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'