global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'swt-production'
    replica: '1'

rule_files:
  - "swt_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # SWT Training Service
  - job_name: 'swt-training'
    static_configs:
      - targets: ['swt-training:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # SWT Live Trading Service  
  - job_name: 'swt-live'
    static_configs:
      - targets: ['swt-live-trader:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']