# SWT Model Configuration
# CRITICAL: Network architectures compatible with Episode 13475

# Network Architecture (Episode 13475 compatible)
network:
  architecture: "standard"               # Episode 13475 used standard architecture
  hidden_dim: 256                        # AUTO-DETECTED from checkpoint
  num_layers: 3                          # VERIFIED: Episode 13475 network depth
  activation: "relu"                     # Standard activation
  dropout: 0.1                           # Standard dropout rate
  
  # Architecture settings (Episode 13475 verified)
  residual_connections: false            # Episode 13475 did not use residuals
  layer_norm: true                       # Layer normalization enabled
  batch_norm: false                      # Batch norm disabled (standard)

# Position Feature Settings (Episode 13475 critical)
position_features:
  enabled: true                          # ALWAYS enabled for Episode 13475
  dimension: 9                           # CRITICAL: Exactly 9 position features
  encoding_type: "standard"              # Standard position encoding
  normalize: true                        # Apply normalization (same as training)

# Value and Reward Network Configuration
value_network:
  value_support_size: 601                # VERIFIED: Episode 13475 value support
  value_support_range: [-300, 300]       # Value distribution range in pips
  
reward_network:
  reward_support_size: 601               # Same as value support
  reward_support_range: [-300, 300]      # Reward distribution range in pips

# Training Configuration (Episode 13475 parameters)
training:
  learning_rate: 0.0002                  # Episode 13475 learning rate
  momentum: 0.9                          # Momentum for optimizer
  weight_decay: 0.0001                   # L2 regularization
  gradient_clipping: 0.5                 # Gradient clipping threshold
  
  # Learning rate schedule
  lr_schedule:
    type: "cosine"                       # Cosine annealing
    warmup_steps: 1000                   # Warmup period
    min_lr: 0.00001                      # Minimum learning rate
  
  # Loss weights (Episode 13475 configuration)
  loss_weights:
    value: 0.25                          # Value loss weight
    reward: 1.0                          # Reward loss weight  
    policy: 1.0                          # Policy loss weight
    consistency: 1.0                     # Consistency loss weight

# Checkpoint Settings
checkpoint:
  save_every: 25                         # Save checkpoint every N episodes
  keep_last: 10                          # Keep last N checkpoints
  save_best: true                        # Always save best performing model
  
  # Episode 13475 specific settings
  episode_13475_format: true             # Use Episode 13475 checkpoint format
  include_optimizer: true                # Save optimizer state
  include_scheduler: true                # Save scheduler state
  include_buffer: true                   # Save experience buffer

# Model Initialization
initialization:
  method: "xavier_uniform"               # Xavier uniform initialization
  gain: 1.0                              # Initialization gain
  
# Episode 13475 Compatibility
episode_13475_compatibility:
  strict_mode: false                     # Relaxed for training new models
  verify_architecture: true              # Verify architecture matches
  verify_features: true                  # Verify feature dimensions
  verify_mcts: true                      # Verify MCTS parameters
